In [1]:
import pandas as pd
import numpy as np

In [2]:
meta_path = "hmp2_metadata_2018-08-20.csv"

In [3]:
meta = pd.read_csv(meta_path, low_memory=False)
trans  = pd.read_csv(
    "host_tx_counts.tsv",
    sep="\t",
    index_col=0
)
micro = pd.read_csv(
    "taxonomic_profiles.tsv",
    sep="\t", 
    index_col=False
)

In [4]:
print("meta:", meta.shape)
print("micro:", micro.shape)
print("trans:", trans.shape)

meta: (5533, 490)
micro: (982, 180)
trans: (55765, 254)

In [5]:
meta.head()

,Project,External ID,Participant ID,site_sub_coll,data_type,week_num,date_of_receipt,interval_days,visit_num,Research Project,...,FecalCal received at MGH:,Proteomics received at LBNL:,Stool Sample ID: Tube A (EtOH),Sample ID: Tube B (No preservative),Tube A and B received at Broad:,stool_id,smoking status,Number years smoked,Age when started smoking,How many cigarettes/cigars/etc. do you smoke per day?
0,C3001CSC1_BP,206615,C3001,C3001CSC1,biopsy_16S,2.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
1,C3001CSC2_BP,206614,C3001,C3001CSC2,biopsy_16S,2.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
2,C3002CSC1_BP,206617,C3002,C3002CSC1,biopsy_16S,0.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
3,C3002CSC2_BP,206619,C3002,C3002CSC2,biopsy_16S,0.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
4,C3002CSC3_BP,206616,C3002,C3002CSC3,biopsy_16S,0.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN

In [6]:
trans.head()

,CSM5FZ1F,CSM5FZ1G,CSM5FZ1H,CSM5FZ1I,CSM5FZ1J,CSM5FZ1K,CSM5FZ1L,CSM5FZ1M,CSM5FZ1N,CSM5FZ1O,...,PSM6XC13,PSM6XC14,PSM6XC15,PSM7J4EU,PSM7J4EV,PSM7J4EW,PSM7J4EX,PSM7J4F3,PSM7J4F4,PSM7J4FL
Transcript,,,,,,,,,,,,,,,,,,,,,
5S_rRNA,0,1,2,1,0,1,0,2,0,0,...,3,1,0,1,0,0,7,1,2,1
7SK,76,37,47,105,103,14,49,115,42,76,...,430,163,56,174,190,200,348,150,407,65
A1BG,0,1,0,1,6,0,1,0,0,0,...,6,3,2,1,1,3,1,4,0,0
A1BG-AS1,31,22,14,66,31,13,45,36,44,123,...,125,101,48,89,75,53,76,55,269,15
A1CF,3638,2225,2360,1923,9506,5579,5636,8965,2149,2777,...,8721,2948,2652,2350,5456,2239,5550,3975,433,3359

In [7]:
micro.head()

,#OTU ID,206646,224324,206619,224326,206624,219644,214995,215058,206750,...,215003,206628,219675,206728,206754,206718,206657,206670,206655,taxonomy
0,IP8BSoli,0.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bacteria; __Proteobacteria; __Alphaproteobacte...
1,UncTepi3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,10.0,0.0,Bacteria; __Proteobacteria; __Betaproteobacter...
2,Unc004ii,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,36.0,Bacteria; __Firmicutes; __Clostridia; __Clostr...
3,Unc00re8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Bacteria; __Bacteroidetes; __Bacteroidia; __Ba...
4,Unc018j2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,Bacteria; __Firmicutes; __Clostridia; __Clostr...

In [8]:
print("First Columns:", micro.columns[:5].tolist())

First Columns: ['#OTU ID', '206646', '224324', '206619', '224326']

In [9]:
trans_T = trans.T

trans_T1= trans.T.reset_index().rename(columns={"index": "External_ID_trans"})

In [10]:
trans_T1.head()

Transcript,External_ID_trans,5S_rRNA,7SK,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,...,snoZ178,snoZ185,snoZ247,snoZ278,snoZ40,snoZ5,snoZ6,snosnR60_Z15,snosnR66,yR211F11.2
0,CSM5FZ1F,0,76,0,31,3638,4185,5,2,0,...,0,0,0,0,0,0,0,0,0,0
1,CSM5FZ1G,1,37,1,22,2225,8957,11,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CSM5FZ1H,2,47,0,14,2360,5066,16,0,0,...,0,0,0,0,0,5,0,0,0,1
3,CSM5FZ1I,1,105,1,66,1923,28636,54,0,0,...,0,0,0,0,0,0,1,0,0,0
4,CSM5FZ1J,0,103,6,31,9506,30395,18,0,0,...,0,0,0,0,0,0,0,0,0,1

In [11]:
# quitar columna OTU
micro = micro.drop(columns=["#OTU ID"])

# poner taxonomy como índice
micro = micro.set_index("taxonomy")
micro.index.name = "External_ID_micro"

micro.shape

(982, 178)

In [12]:
micro_T = micro.T
micro_T.index.name = "External_ID_micro"

micro_T.shape

(178, 982)

In [13]:
micro_T.head()

External_ID_micro,Bacteria; __Proteobacteria; __Alphaproteobacteria; __Rhodospirillales; __Acetobacteraceae; __Belnapia,Bacteria; __Proteobacteria; __Betaproteobacteria; __Burkholderiales; __Comamonadaceae; __Tepidimonas,Bacteria; __Firmicutes; __Clostridia; __Clostridiales; __Christensenellaceae; __Christensenellaceae_R_7_group,Bacteria; __Bacteroidetes; __Bacteroidia; __Bacteroidales; __Prevotellaceae; __Prevotella,Bacteria; __Firmicutes; __Clostridia; __Clostridiales; __Family_XIII; __Family_XIII_AD3011_group,Bacteria; __Proteobacteria; __Alphaproteobacteria; __Rhodobacterales; __Rhodobacteraceae; __Paracoccus,Bacteria; __Firmicutes; __Clostridia; __Clostridiales; __Ruminococcaceae; __Ruminiclostridium,Bacteria; __Proteobacteria; __Gammaproteobacteria; __Run_SP154; __f; __g,Bacteria; __Proteobacteria; __Gammaproteobacteria; __Pasteurellales; __Pasteurellaceae; __Frederiksenia,Bacteria; __Actinobacteria; __Actinobacteria; __Corynebacteriales; __Corynebacteriaceae; __Corynebacterium_1,...,Bacteria; __Firmicutes; __Clostridia; __Clostridiales; __Clostridiales_vadinBB60_group; __g,Bacteria; __Bacteroidetes; __Bacteroidia; __Bacteroidales; __Prevotellaceae; __Prevotella,Bacteria; __Tenericutes; __Mollicutes; __Mollicutes_RF9; __f; __g,Bacteria; __Proteobacteria; __Alphaproteobacteria; __Rhodospirillales; __Rhodospirillales_Incertae_Sedis; __Candidatus_Alysiosphaera,Bacteria; __Firmicutes; __Clostridia; __Clostridiales; __Ruminococcaceae; __Ruminococcus_1,Bacteria; __Firmicutes; __Clostridia; __Clostridiales; __Lachnospiraceae; __Blautia,Bacteria; __Bacteroidetes; __Sphingobacteriia; __Sphingobacteriales; __Saprospiraceae; __uncultured,Bacteria; __Firmicutes; __Clostridia; __Clostridiales; __Lachnospiraceae; __Roseburia,Bacteria; __Firmicutes; __Clostridia; __Clostridiales; __Lachnospiraceae; __uncultured,Bacteria; __Firmicutes; __Clostridia; __Clostridiales; __Ruminococcaceae; __Ruminococcaceae_UCG_014
External_ID_micro,,,,,,,,,,,,,,,,,,,,,
206646,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,481.0,0.0,0.0,0.0,0.0
224324,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0
206619,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
224326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,117.0,0.0,0.0,0.0,0.0
206624,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
# micro_T
d_micro = micro_T.reset_index().duplicated(keep=False).sum()
print("Exact duplicates on micro_T:", int(d_micro))

# trans_T1
d_trans = trans_T1.reset_index().duplicated(keep=False).sum()
print("Exact duplicates on trans_T1:", int(d_trans))

# meta
d_meta = meta.duplicated(keep=False).sum()
print("Exact duplicates on meta:", int(d_meta))

Exact duplicates on micro_T: 0
Exact duplicates on trans_T1: 0
Exact duplicates on meta: 0

In [15]:
cols = ['External ID', 'Participant ID', 'week_num', 'visit_num', 'site_sub_coll', 'data_type']

dup_count = meta.duplicated(subset=cols, keep=False).sum()
print("Duplicates on External ID, participant ID, week_num, visit_num, site_sub and datatype:", int(dup_count))

Duplicates on External ID, participant ID, week_num, visit_num, site_sub and datatype: 0

In [16]:
meta["data_type"].value_counts(dropna=False)

data_type
metagenomics            1638
metatranscriptomics      835
viromics                 703
metabolomics             546
proteomics               450
methylome                449
host_transcriptomics     252
serology                 210
stool_16S                180
biopsy_16S               178
host_genome               92
Name: count, dtype: int64

In [17]:
site_set  = set(meta["External ID"].astype(str).str.strip().dropna())
micro_set = set(micro_T.index.astype(str).str.strip())  # asumiendo index = External_id_micro

matches = site_set & micro_set
matches_list = sorted(matches)

print("Matches:", len(matches))
print("Matches 50 first:", matches_list[:50])
print("site_sub_coll unique:", len(site_set))
print("eExternal_ID_micro unique:", len(micro_set))

Matches: 178
Matches 50 first: ['206534', '206536', '206538', '206547', '206548', '206561', '206562', '206563', '206564', '206569', '206570', '206571', '206572', '206603', '206604', '206605', '206608', '206609', '206614', '206615', '206616', '206617', '206618', '206619', '206620', '206621', '206622', '206623', '206624', '206625', '206626', '206627', '206628', '206629', '206630', '206635', '206636', '206643', '206644', '206645', '206646', '206647', '206648', '206655', '206656', '206657', '206658', '206659', '206660', '206667']
site_sub_coll unique: 2892
eExternal_ID_micro unique: 178

In [18]:
dup_count = micro_T.index.duplicated(keep=False).sum()
print("Duplicates at External_id_micro (index):", int(dup_count))

Duplicates at External_id_micro (index): 0

In [19]:
meta_matches = meta[meta["External ID"].astype(str).str.strip().isin(matches)]
print(meta_matches["data_type"].value_counts(dropna=False))

data_type
biopsy_16S    178
Name: count, dtype: int64

In [20]:
meta_set  = set(meta["External ID"].astype(str).str.strip().dropna())
trans_set = set(trans_T1["External_ID_trans"].astype(str).str.strip())

matches_tx = meta_set & trans_set
matches_tx_list = sorted(matches_tx)

print("Matches:", len(matches_tx_list))
print("Matches 50 first:", matches_tx_list[:50])
print("External ID unique (meta):", len(meta_set))
print("External_ID_trans unique (trans_T1 index):", len(trans_set))

# data_type de esos matches en meta
meta_matches_tx = meta[meta["External ID"].astype(str).str.strip().isin(matches_tx)]
print("\nCount data_type on those matches:")
print(meta_matches_tx["data_type"].value_counts(dropna=False))

Matches: 251
Matches 50 first: ['CSM5FZ1F', 'CSM5FZ1G', 'CSM5FZ1H', 'CSM5FZ1I', 'CSM5FZ1J', 'CSM5FZ1K', 'CSM5FZ1L', 'CSM5FZ1M', 'CSM5FZ1N', 'CSM5FZ1O', 'CSM5FZ1Q', 'CSM5FZ1R', 'CSM5FZ1S', 'CSM5FZ1T', 'CSM5FZ1U', 'CSM5FZ1V', 'CSM5FZ1W', 'CSM5FZ22', 'CSM5FZ23', 'CSM5FZ24', 'CSM5FZ27', 'CSM5FZ28', 'CSM5FZ29', 'CSM5FZ2A', 'CSM5FZ2B', 'CSM5FZ2C', 'CSM5FZ2D', 'CSM5FZ2E', 'CSM5FZ2F', 'CSM5FZ2G', 'CSM5FZ2H', 'CSM5FZ2I', 'CSM5FZ2L', 'CSM5FZ2M', 'CSM5FZ2N', 'CSM5FZ2O', 'CSM5FZ2P', 'CSM5FZ2Q', 'CSM5FZ2R', 'CSM5FZ2S', 'CSM5FZ2T', 'CSM5FZ34', 'CSM5FZ35', 'CSM5FZ36', 'CSM5FZ37', 'CSM5FZ38', 'CSM5FZ39', 'CSM5FZ3A', 'CSM5FZ3B', 'CSM5FZ3C']
External ID unique (meta): 2892
External_ID_trans unique (trans_T1 index): 254

Count data_type on those matches:
data_type
host_transcriptomics    251
methylome               218
host_genome               1
Name: count, dtype: int64

In [21]:
# quedarnos SOLO con host_transcriptomics y biopsy_16S en meta
keep_types = ["host_transcriptomics", "biopsy_16S"]

meta_clean = meta[meta["data_type"].astype(str).str.strip().isin(keep_types)].copy()

print("meta original:", meta.shape)
print("meta_clean:", meta_clean.shape)
print(meta_clean["data_type"].value_counts(dropna=False))

meta original: (5533, 490)
meta_clean: (430, 490)
data_type
host_transcriptomics    252
biopsy_16S              178
Name: count, dtype: int64

In [22]:
meta_set  = set(meta_clean["External ID"].astype(str).str.strip().dropna())
trans_set = set(trans_T1["External_ID_trans"].astype(str).str.strip())   

matches_tx = meta_set & trans_set
matches_tx_list = sorted(matches_tx)

print("Matches:", len(matches_tx_list))
print("Matches 50 first:", matches_tx_list[:50])
print("External ID unique (meta_clean):", len(meta_set))
print("External_ID_trans unique (trans_T1 index):", len(trans_set))

# data_type de esos matches en meta_clean
meta_matches_tx = meta_clean[meta_clean["External ID"].astype(str).str.strip().isin(matches_tx)]
print("\nCount data_type on match (meta_clean):")
print(meta_matches_tx["data_type"].astype(str).str.strip().value_counts(dropna=False))

Matches: 251
Matches 50 first: ['CSM5FZ1F', 'CSM5FZ1G', 'CSM5FZ1H', 'CSM5FZ1I', 'CSM5FZ1J', 'CSM5FZ1K', 'CSM5FZ1L', 'CSM5FZ1M', 'CSM5FZ1N', 'CSM5FZ1O', 'CSM5FZ1Q', 'CSM5FZ1R', 'CSM5FZ1S', 'CSM5FZ1T', 'CSM5FZ1U', 'CSM5FZ1V', 'CSM5FZ1W', 'CSM5FZ22', 'CSM5FZ23', 'CSM5FZ24', 'CSM5FZ27', 'CSM5FZ28', 'CSM5FZ29', 'CSM5FZ2A', 'CSM5FZ2B', 'CSM5FZ2C', 'CSM5FZ2D', 'CSM5FZ2E', 'CSM5FZ2F', 'CSM5FZ2G', 'CSM5FZ2H', 'CSM5FZ2I', 'CSM5FZ2L', 'CSM5FZ2M', 'CSM5FZ2N', 'CSM5FZ2O', 'CSM5FZ2P', 'CSM5FZ2Q', 'CSM5FZ2R', 'CSM5FZ2S', 'CSM5FZ2T', 'CSM5FZ34', 'CSM5FZ35', 'CSM5FZ36', 'CSM5FZ37', 'CSM5FZ38', 'CSM5FZ39', 'CSM5FZ3A', 'CSM5FZ3B', 'CSM5FZ3C']
External ID unique (meta_clean): 430
External_ID_trans unique (trans_T1 index): 254

Count data_type on match (meta_clean):
data_type
host_transcriptomics    251
Name: count, dtype: int64

In [23]:
meta_ids_clean  = set(meta_clean["External ID"].astype(str).str.strip().dropna())
trans_ids       = set(trans_T1["External_ID_trans"].astype(str).str.strip())

missing_in_meta = sorted(trans_ids - meta_ids_clean)

print("IDs in trans_T1 that are NOT in clean :", len(missing_in_meta))
print(missing_in_meta)

IDs in trans_T1 that are NOT in clean : 3
['CSMDRVY8', 'CSMDRVY9', 'HSm9JTBX']

In [24]:
meta_ids_all = set(meta["External ID"].astype(str).str.strip().dropna())
missing_in_meta_all = sorted(trans_ids - meta_ids_all)

print("IDs in trans_T1 that are NOT in meta :", len(missing_in_meta_all))
print(missing_in_meta_all)

IDs in trans_T1 that are NOT in meta : 3
['CSMDRVY8', 'CSMDRVY9', 'HSm9JTBX']

In [25]:
orphans = ['CSMDRVY8', 'CSMDRVY9', 'HSm9JTBX']

trans_T1_clean = trans_T1[~trans_T1["External_ID_trans"].astype(str).str.strip().isin(orphans)].copy()

print("trans_T1 original:", trans_T1.shape)
print("trans_T1 clean (no orphans):", trans_T1_clean.shape)

trans_T1 original: (254, 55766)
trans_T1 clean (no orphans): (251, 55766)

In [26]:
meta_clean.to_csv("meta_clean.csv", index=False)
print("Saved as meta_clean.csv")

Saved as meta_clean.csv

In [27]:
cols = ["Participant ID", "visit_num", "data_type", "week_num"]

dup_count = meta_clean.duplicated(subset=cols, keep=False).sum()
print("Duplicate rows Participant ID + visit_num + data_type:", int(dup_count))


dups = meta_clean.loc[meta_clean.duplicated(subset=cols, keep=False), cols].sort_values(cols)
dups.head(50)

Duplicate rows Participant ID + visit_num + data_type: 417

    Participant ID  visit_num             data_type  week_num
0            C3001          1            biopsy_16S       2.0
1            C3001          1            biopsy_16S       2.0
2            C3002          1            biopsy_16S       0.0
3            C3002          1            biopsy_16S       0.0
4            C3002          1            biopsy_16S       0.0
5            C3002          1            biopsy_16S       0.0
270          C3002          1  host_transcriptomics       0.0
271          C3002          1  host_transcriptomics       0.0
272          C3002          1  host_transcriptomics       0.0
273          C3002          1  host_transcriptomics       0.0
6            C3003          1            biopsy_16S       1.0
7            C3003          1            biopsy_16S       1.0
8            C3003          1            biopsy_16S       1.0
274          C3003          1  host_transcriptomics       1.0
275          C3003          1  host_transcriptomics       1.0
276          C3003          1  host_transcriptomics       1.0
9            C3004          1            biopsy_16S       0.0
10           C3004          1            biopsy_16S       0.0
11           C3004          1            biopsy_16S       0.0
12           C3004          1            biopsy_16S       0.0
277          C3004          1  host_transcriptomics       0.0
278          C3004          1  host_transcriptomics       0.0
279          C3004          1  host_transcriptomics       0.0
13           C3005          1            biopsy_16S       0.0
14           C3005          1            biopsy_16S       0.0
280          C3005          1  host_transcriptomics       0.0
281          C3005          1  host_transcriptomics       0.0
282          C3005          1  host_transcriptomics       0.0
15           C3006          1            biopsy_16S       0.0
16           C3006          1            biopsy_16S       0.0
283          C3006          1  host_transcriptomics       0.0
284          C3006          1  host_transcriptomics       0.0
285          C3006          1  host_transcriptomics       0.0
286          C3006          1  host_transcriptomics       0.0
287          C3008          1  host_transcriptomics       0.0
288          C3008          1  host_transcriptomics       0.0
289          C3008          1  host_transcriptomics       0.0
290          C3010          1  host_transcriptomics       0.0
291          C3010          1  host_transcriptomics       0.0
292          C3010          1  host_transcriptomics       0.0
17           C3011          1            biopsy_16S       4.0
18           C3011          1            biopsy_16S       4.0
293          C3011          1  host_transcriptomics       4.0
294          C3011          1  host_transcriptomics       4.0
295          C3011          1  host_transcriptomics       4.0
296          C3012          1  host_transcriptomics       0.0
297          C3012          1  host_transcriptomics       0.0
298          C3012          1  host_transcriptomics       0.0
299          C3013          1  host_transcriptomics       0.0
300          C3013          1  host_transcriptomics       0.0

In [28]:
key = ["Participant ID","week_num","visit_num","data_type"]

grp = meta_clean.groupby(key).size().reset_index(name="n")
dups = grp[grp["n"] > 1].sort_values("n", ascending=False)

print("Duplicate groups (n>1):", dups.shape[0])
print("Top 20:")
print(dups.head(50))

Duplicate groups (n>1): 172
Top 20:
    Participant ID  week_num  visit_num             data_type  n
1            C3002       0.0          1            biopsy_16S  4
5            C3004       0.0          1            biopsy_16S  4
24           C3021       2.0          1  host_transcriptomics  4
33           C3029       0.0          1  host_transcriptomics  4
10           C3006       0.0          1  host_transcriptomics  4
35           C3030       0.0          1  host_transcriptomics  4
2            C3002       0.0          1  host_transcriptomics  4
43           C3035       0.0          1  host_transcriptomics  3
45           C3037       0.0          1  host_transcriptomics  3
46           E5004       0.0          1  host_transcriptomics  3
47           E5009       0.0          1  host_transcriptomics  3
84           H4019      21.0         32  host_transcriptomics  3
48           E5013       0.0          1  host_transcriptomics  3
54           H4004      46.0         32  host_transcriptomics  3
117          M2008      53.0         32  host_transcriptomics  3
74           H4015       0.0          1  host_transcriptomics  3
76           H4016       1.0          1  host_transcriptomics  3
78           H4017       0.0          1  host_transcriptomics  3
80           H4018       0.0          1  host_transcriptomics  3
82           H4019       0.0          1  host_transcriptomics  3
90           H4023       0.0          1  host_transcriptomics  3
88           H4022       0.0          1  host_transcriptomics  3
39           C3032       1.0          1  host_transcriptomics  3
92           H4024       0.0          1  host_transcriptomics  3
93           H4027       0.0          1  host_transcriptomics  3
129          M2026       0.0          1  host_transcriptomics  3
95           H4028       0.0          1  host_transcriptomics  3
128          M2026       0.0          1            biopsy_16S  3
98           H4031       0.0          1  host_transcriptomics  3
99           H4032       0.0          1  host_transcriptomics  3
101          H4035       0.0          1  host_transcriptomics  3
103          H4038       0.0          1  host_transcriptomics  3
105          H4039       0.0          1  host_transcriptomics  3
107          H4040       1.0          1  host_transcriptomics  3
113          H4045       2.0          1  host_transcriptomics  3
114          M2008       0.0          1            biopsy_16S  3
41           C3034       0.0          1  host_transcriptomics  3
115          M2008       0.0          1  host_transcriptomics  3
11           C3008       0.0          1  host_transcriptomics  3
6            C3004       0.0          1  host_transcriptomics  3
14           C3011       4.0          1  host_transcriptomics  3
12           C3010       0.0          1  host_transcriptomics  3
22           C3017       0.0          1  host_transcriptomics  3
18           C3015       1.0          1  host_transcriptomics  3
171          P6016       2.0          1            biopsy_16S  3
8            C3005       0.0          1  host_transcriptomics  3
28           C3023       0.0          1  host_transcriptomics  3
16           C3013       0.0          1  host_transcriptomics  3
15           C3012       0.0          1  host_transcriptomics  3
172          P6016       2.0          1  host_transcriptomics  3

In [29]:
key = ["Participant ID","week_num","visit_num","data_type"]

grp = meta_clean.groupby(key).size().reset_index(name="n")
print("Duplicate groups (n>1):", (grp["n"]>1).sum())
print("Total rows in duplicates:", int(grp.loc[grp["n"]>1, "n"].sum()))

Duplicate groups (n>1): 172
Total rows in duplicates: 406

In [30]:
key = ["Participant ID","week_num","visit_num","data_type"]

diag = (meta_clean.groupby(key)
        .agg(n_rows=("External ID","size"),
             n_external_ids=("External ID","nunique"))
        .reset_index()
        .sort_values(["n_rows","n_external_ids"], ascending=False))

print(diag.head(20))

   Participant ID  week_num  visit_num             data_type  n_rows  \
1           C3002       0.0          1            biopsy_16S       4
2           C3002       0.0          1  host_transcriptomics       4
5           C3004       0.0          1            biopsy_16S       4
10          C3006       0.0          1  host_transcriptomics       4
24          C3021       2.0          1  host_transcriptomics       4
33          C3029       0.0          1  host_transcriptomics       4
35          C3030       0.0          1  host_transcriptomics       4
3           C3003       1.0          1            biopsy_16S       3
4           C3003       1.0          1  host_transcriptomics       3
6           C3004       0.0          1  host_transcriptomics       3
8           C3005       0.0          1  host_transcriptomics       3
11          C3008       0.0          1  host_transcriptomics       3
12          C3010       0.0          1  host_transcriptomics       3
14          C3011       4.0          1  host_transcriptomics       3
15          C3012       0.0          1  host_transcriptomics       3
16          C3013       0.0          1  host_transcriptomics       3
18          C3015       1.0          1  host_transcriptomics       3
20          C3016       0.0          1  host_transcriptomics       3
22          C3017       0.0          1  host_transcriptomics       3
28          C3023       0.0          1  host_transcriptomics       3

    n_external_ids
1                4
2                4
5                4
10               4
24               4
33               4
35               4
3                3
4                3
6                3
8                3
11               3
12               3
14               3
15               3
16               3
18               3
20               3
22               3
28               3

In [31]:
keyran = ["Participant ID","week_num","visit_num","data_type"]

meta_dedup_first = (
    meta_clean
    .drop_duplicates(subset=keyran, keep="first")
)

print("meta_clean:", meta_clean.shape)
print("meta_dedup_first:", meta_dedup_first.shape)
print("Duplicates after:", meta_dedup_first.duplicated(subset=keyran, keep=False).sum())

meta_clean: (430, 490)
meta_dedup_first: (190, 490)
Duplicates after: 0

In [32]:
#ver como está de repetidos en diferentes visitas, mismo paciente y mismo tipo de datos 

keyex = ["Participant ID", "data_type"]

grp = meta_dedup_first.groupby(keyex).size().reset_index(name="n")
dups = grp[grp["n"] > 1].sort_values("n", ascending=False)

print("Groups with more than one visit (n>1):", dups.shape[0])
print(dups.head(20))

Groups with more than one visit (n>1): 19
    Participant ID             data_type  n
51           H4004            biopsy_16S  2
112          M2021            biopsy_16S  2
158          P6016            biopsy_16S  2
137          M2064  host_transcriptomics  2
121          M2028  host_transcriptomics  2
120          M2028            biopsy_16S  2
115          M2025  host_transcriptomics  2
114          M2025            biopsy_16S  2
113          M2021  host_transcriptomics  2
109          M2008  host_transcriptomics  2
52           H4004  host_transcriptomics  2
108          M2008            biopsy_16S  2
76           H4019  host_transcriptomics  2
75           H4019            biopsy_16S  2
58           H4008  host_transcriptomics  2
57           H4008            biopsy_16S  2
56           H4007  host_transcriptomics  2
55           H4007            biopsy_16S  2
159          P6016  host_transcriptomics  2

In [33]:
#entonces hay que escoger siempre la primera visita evitando cambios en el tratamiento 


key_visit = ["Participant ID", "week_num", "visit_num"]
keep_types = {"host_transcriptomics", "biopsy_16S"}

# 1) identificar visitas (por participant/week/visit) donde están ambos data_type
v = (meta_dedup_first[meta_dedup_first["data_type"].isin(keep_types)]
     .groupby(key_visit)["data_type"].nunique()
     .reset_index(name="n_types"))

both = v[v["n_types"] == 2].copy()

# 2) para cada Participant, elegir la "primera" visita (orden por week_num y luego visit_num)
first_visit = (both.sort_values(["Participant ID", "week_num", "visit_num"])
               .drop_duplicates(subset=["Participant ID"], keep="first"))

print("Participants with at least onw visit in both:", first_visit.shape[0])

# 3) quedarnos con esas visitas y conservar las 2 filas (host_transcriptomics + biopsy_16S)
meta_first_pair = (meta_dedup_first
                   .merge(first_visit[key_visit], on=key_visit, how="inner")
                   .query("data_type in ['host_transcriptomics','biopsy_16S']")
                   .copy())

print("Result (Should be 2 rows per participant):", meta_first_pair.shape)
print(meta_first_pair["data_type"].value_counts(dropna=False))

Participants with at least onw visit in both: 77
Result (Should be 2 rows per participant): (154, 490)
data_type
biopsy_16S              77
host_transcriptomics    77
Name: count, dtype: int64

In [34]:
#revisar que hay uno por cada participante 
chk = meta_first_pair.groupby("Participant ID").size().value_counts()
print(chk)   # idealmente todo debe ser 2

2    77
Name: count, dtype: int64

In [35]:
dx_counts = (
    meta_first_pair
    .drop_duplicates(subset=["Participant ID"])
    ["diagnosis"]
    .value_counts(dropna=False)
)

dx_counts

diagnosis
CD        34
UC        22
nonIBD    21
Name: count, dtype: int64

In [36]:

def _clean_series(s: pd.Series) -> pd.Series:
    return s.astype(str).str.strip()

def _clean_index(idx: pd.Index) -> pd.Index:
    return pd.Index(idx.astype(str)).str.strip()

key_visit = ["Participant ID", "week_num", "visit_num"]

In [37]:
# 1) Asegurar MICRO: index = External_ID_micro

micro_tbl = micro_T.copy()

micro_tbl.index = _clean_index(micro_tbl.index)
micro_tbl.index.name = "External_ID_micro"

# (Opcional) sanity
print("micro_tbl index name:", micro_tbl.index.name)
print("micro_tbl duplicated index:", int(micro_tbl.index.duplicated().sum()))

# prefijo para evitar choques de nombres
micro_tbl = micro_tbl.add_prefix("micro__")

micro_tbl index name: External_ID_micro
micro_tbl duplicated index: 0

In [38]:
# 2) Asegurar TRANS: index = External_ID_trans
#    (si ya existe como columna, lo pasamos a index)

trans_tbl = trans_T1_clean.copy()

if "External_ID_trans" in trans_tbl.columns:
    trans_tbl["External_ID_trans"] = _clean_series(trans_tbl["External_ID_trans"])
    trans_tbl = trans_tbl.set_index("External_ID_trans", drop=True)

trans_tbl.index = _clean_index(trans_tbl.index)
trans_tbl.index.name = "External_ID_trans"

print("trans_tbl index name:", trans_tbl.index.name)
print("trans_tbl duplicated index:", int(trans_tbl.index.duplicated().sum()))

# prefijo para evitar choques de nombres
trans_tbl = trans_tbl.add_prefix("tx__")

trans_tbl index name: External_ID_trans
trans_tbl duplicated index: 0

In [39]:
# 3) Preparar meta por rama (tx vs micro)

meta2 = meta_clean.copy()
meta2["External ID"] = _clean_series(meta2["External ID"])
meta2["data_type"] = meta2["data_type"].astype(str).str.strip()

meta_tx = (meta2[meta2["data_type"] == "host_transcriptomics"]
           [key_visit + ["External ID"]]
           .rename(columns={"External ID": "External_ID_trans"})
           .drop_duplicates())

meta_micro = (meta2[meta2["data_type"] == "biopsy_16S"]
              [key_visit + ["External ID"]]
              .rename(columns={"External ID": "External_ID_micro"})
              .drop_duplicates())

print("meta_tx:", meta_tx.shape, " | meta_micro:", meta_micro.shape)

meta_tx: (252, 4)  | meta_micro: (178, 4)

In [40]:
# 4) MERGES paralelos (clave está en meta, features están indexadas)

tx_branch = meta_tx.merge(trans_tbl, left_on="External_ID_trans", right_index=True, how="inner")
micro_branch = meta_micro.merge(micro_tbl, left_on="External_ID_micro", right_index=True, how="inner")

print("tx_branch:", tx_branch.shape)
print("micro_branch:", micro_branch.shape)

tx_branch: (251, 55769)
micro_branch: (178, 986)

In [41]:
# 1 fila por visita con ambos omics

micro_cols = [c for c in micro_branch.columns if c.startswith("micro__")]
micro_only = micro_branch[key_visit + ["External_ID_micro"] + micro_cols].copy()

df_all = tx_branch.merge(micro_only, on=key_visit, how="inner")

print("df_all:", df_all.shape)
print("Participantes:", df_all["Participant ID"].nunique())

#  revisar duplicados por visita final
print("Duplicates per visit @ df_all:", int(df_all.duplicated(subset=key_visit).sum()))

df_all: (441, 60764)
Participantes: 79
Duplicates per visit @ df_all: 353

In [42]:

seed = 42
rng = np.random.default_rng(seed)

keep_types = ["host_transcriptomics", "biopsy_16S"]
key_visit = ["Participant ID", "week_num", "visit_num"]
key_pick  = ["Participant ID", "week_num", "visit_num", "data_type"]

m = meta_clean.copy()
m.columns = m.columns.astype(str).str.strip()
m["data_type"] = m["data_type"].astype(str).str.strip()
m["External ID"] = m["External ID"].astype(str).str.strip()

# 0) quedarnos solo con los dos tipos
m = m[m["data_type"].isin(keep_types)].copy()

# 1) visitas donde existen ambos tipos
both = (m.groupby(key_visit)["data_type"].nunique().reset_index(name="n_types"))
both = both[both["n_types"] == 2].copy()

# 2) primera visita por Participant ID (más temprana)
first_visit = (both.sort_values(["Participant ID", "week_num", "visit_num"])
                  .drop_duplicates(subset=["Participant ID"], keep="first"))

# 3) quedarnos SOLO con filas de esa primera visita
m_first = m.merge(first_visit[key_visit], on=key_visit, how="inner").copy()

# 4) si hay duplicados por tipo dentro de esa visita, elegir 1 al azar por tipo
m_first["_r"] = rng.random(len(m_first))
meta_pair = (m_first.sort_values(key_pick + ["_r"])
                    .drop_duplicates(subset=key_pick, keep="first")
                    .drop(columns="_r"))

print("meta_pair shape:", meta_pair.shape)
print(meta_pair["data_type"].value_counts())

# sanity: idealmente 2 filas por participante (una por tipo)
print(meta_pair.groupby("Participant ID").size().value_counts())

meta_pair shape: (154, 490)
data_type
biopsy_16S              77
host_transcriptomics    77
Name: count, dtype: int64
2    77
Name: count, dtype: int64

In [43]:
key_visit = ["Participant ID","week_num","visit_num"]

# --- 1) Separar ramas y renombrar External IDs ---
meta_tx = meta_pair[meta_pair["data_type"]=="host_transcriptomics"].rename(columns={"External ID":"External_ID_trans"}).copy()
meta_micro = meta_pair[meta_pair["data_type"]=="biopsy_16S"].rename(columns={"External ID":"External_ID_micro"}).copy()

# --- 2) MICRO features (index = External_ID_micro) ---
micro_tbl = micro_T.copy()
micro_tbl.index = micro_tbl.index.astype(str).str.strip()
micro_tbl.index.name = "External_ID_micro"
micro_tbl = micro_tbl.add_prefix("micro__")

# --- 3) TRANS features (puede ser index o columna; lo dejamos como index sí o sí) ---
trans_tbl = trans_T1.copy()
if "External_ID_trans" in trans_tbl.columns:
    trans_tbl["External_ID_trans"] = trans_tbl["External_ID_trans"].astype(str).str.strip()
    trans_tbl = trans_tbl.set_index("External_ID_trans")

trans_tbl.index = trans_tbl.index.astype(str).str.strip()
trans_tbl.index.name = "External_ID_trans"
trans_tbl = trans_tbl.add_prefix("tx__")

# --- 4) Merge paralelo por External ID ---
tx_branch = meta_tx.merge(trans_tbl, left_on="External_ID_trans", right_index=True, how="inner")
micro_branch = meta_micro.merge(micro_tbl, left_on="External_ID_micro", right_index=True, how="inner")

print("tx_branch:", tx_branch.shape)
print("micro_branch:", micro_branch.shape)

# --- 5) Preparar lo que agregamos desde micro ---
# A) features micro
micro_feat_cols = [c for c in micro_branch.columns if c.startswith("micro__")]

# B) metadata micro que NO está ya en tx_branch (para conservar "todo" sin choques)
micro_meta_cols = [
    c for c in micro_branch.columns
    if (c not in key_visit)
    and (c not in micro_feat_cols)
    and (c != "External_ID_micro")
    and (c != "data_type")
    and (c not in tx_branch.columns)
]

micro_only = micro_branch[key_visit + ["External_ID_micro"] + micro_meta_cols + micro_feat_cols].copy()

# prefijar metadata micro para que quede claro que viene del renglón 16S
rename_micro_meta = {c: f"micro_meta__{c}" for c in micro_meta_cols}
micro_only = micro_only.rename(columns=rename_micro_meta)

# --- 6) DF FINAL: conservar TODA la metadata (desde tx_branch) + sumar micro ---
# (tx_branch ya trae toda la metadata original + tx__features)
df_all = tx_branch.merge(micro_only, on=key_visit, how="inner", validate="1:1")

print("df_all:", df_all.shape)
print("Duplicates per visit:", df_all.duplicated(subset=key_visit, keep=False).sum())
print("Participants:", df_all["Participant ID"].nunique())

tx_branch: (77, 56255)
micro_branch: (77, 1472)
df_all: (77, 61250)
Duplicates per visit: 0
Participants: 77

In [44]:
# guardar a CSV
out_path = "df_all_tx_micro.csv"
df_all.to_csv(out_path, index=False)

print("Saved @:", out_path)

Saved @: df_all_tx_micro.csv